[package]
name = "01_basic_ping_bot"
version = "0.1.0"
authors = ["my name <my@email.address>", "Anthony Guéchoum <a.guechoum@gmail.com>"]

[dependencies]
serenity = "0.5"
reqwest = "0.8.1"
html2runes = "1.0.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
<<<<<<< HEAD
html5ever = "0.13"
=======
victoria-dom = "0.1"
unicode-segmentation = "1.1.0"
>>>>>>> 1ac10d9e9556999c6d7d5b26ec3478f20b7cafdd
